---
name: Package RBDyn
on:
  repository_dispatch:
    types:
    - package-master
    - package-release
  push:
    paths-ignore:
    - doc/**
    - README.md
    - ".github/workflows/build.yml"
    branches:
    - "**"
    tags:
    - v*
  pull_request:
    branches:
    - "**"
jobs:
  check-tag:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
      if: startsWith(github.ref, 'refs/tags/')
    - name: Check version coherency
      run: |
        set -x
        export VERSION=`echo ${{ github.ref }} | sed -e 's@refs/tags/v@@'`
        echo "::set-env name=REJECTION::PROJECT_VERSION in CMakeLists.txt does not match tag"
        grep -q "set(PROJECT_VERSION ${VERSION})" CMakeLists.txt
        echo "::set-env name=REJECTION::Upstream version in debian/changelog does not match tag"
        head -n 1 debian/changelog | grep -q "rbdyn (${VERSION}"
        echo "::set-env name=REJECTION::Conan package version does not match tag"
        grep -q '    version = "${VERSION}"' conanfile.py
        echo "::set-env name=REJECTION::"
        export TAG=`echo ${{ github.ref }} | sed -e 's@refs/tags/@@'`
        echo "::set-env name=RELEASE_TAG::${TAG}"
      if: startsWith(github.ref, 'refs/tags/')
    - name: Delete tag
      run: |
        set -x
        curl --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' -X DELETE https://api.github.com/repos/${{ github.repository }}/git/${{ github.ref }}
      if: failure()
    - name: Notify tag deletion
      uses: archive/github-actions-slack@master
      with:
        slack-bot-user-oauth-access-token: "${{ secrets.SLACK_BOT_TOKEN }}"
        slack-channel: "#ci"
        slack-text: |
          Tag *${{ github.ref }}* in *${{ github.repository }}* was deleted:
            ${{ env.REJECTION}}
      if: failure()
    - name: Create release
      uses: jrl-umi3218/github-actions/create-release@master
      with:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        tag: "${{ env.RELEASE_TAG }}"
      if: startsWith(github.ref, 'refs/tags/')
  build-packages:
    needs: check-tag
    strategy:
      fail-fast: false
      matrix:
        dist:
        - xenial
        - bionic
        - focal
        arch:
        - i386
        - amd64
        exclude:
        - dist: focal
          arch: i386
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Choose extra mirror
      run: |
        # We upload in all conditions except when building on PR or branch other than master
        export PACKAGE_UPLOAD=true
        if ${{ startsWith(github.ref, 'refs/tags/') }}
        then
          export USE_HEAD=false
        elif [ "${{ github.event.action }}" == "package-master" ]
        then
          export USE_HEAD=true
        elif [ "${{ github.event.action }}" == "package-release" ]
        then
          export USE_HEAD=false
          export REF=`git tag --sort=committerdate --list 'v[0-9]*'|tail -1`
          git checkout $REF
          git submodule sync && git submodule update
        else
          export REF=`echo ${{ github.ref }} | sed -e 's@refs/[a-z]*/@@'`
          export USE_HEAD=true
          if [ $REF != "master" ]
          then
            export PACKAGE_UPLOAD=false
          fi
        fi
        if $USE_HEAD
        then
          echo "::set-env name=BINTRAY_REPO::multi-contact-head"
          echo "::set-env name=BINTRAY_VERSION::HEAD"
          echo "::set-env name=EXTRA_MIRROR::https://dl.bintray.com/gergondet/multi-contact-head"
          echo "::set-env name=PACKAGE_JOB::package-master"
        else
          echo "::set-env name=BINTRAY_REPO::multi-contact-release"
          echo "::set-env name=BINTRAY_VERSION::${REF}"
          echo "::set-env name=EXTRA_MIRROR::https://dl.bintray.com/gergondet/multi-contact-release"
          echo "::set-env name=PACKAGE_JOB::package-release"
        fi
        echo "::set-env name=PACKAGE_UPLOAD::${PACKAGE_UPLOAD}"
    - name: Build package
      uses: jrl-umi3218/github-actions/build-package-native@master
      with:
        dist: "${{ matrix.dist }}"
        arch: "${{ matrix.arch }}"
        other-mirrors: "${{ env.EXTRA_MIRROR }}"
        other-gpg-keys: '0x892EA6EE273707C6495A6FB6220D644C64666806'
    - uses: actions/upload-artifact@v1
      with:
        name: packages-${{ matrix.dist }}-${{ matrix.arch }}
        path: "/tmp/packages-${{ matrix.dist }}-${{ matrix.arch }}/"
      if: env.PACKAGE_UPLOAD == 'true'
  upload-packages:
    needs: build-packages
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        dist:
        - xenial
        - bionic
        - focal
        arch:
        - i386
        - amd64
        exclude:
        - dist: focal
          arch: i386
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Choose extra mirror
      run: |
        # We upload in all conditions except when building on PR or branch other than master
        export PACKAGE_UPLOAD=true
        if ${{ startsWith(github.ref, 'refs/tags/') }}
        then
          export USE_HEAD=false
        elif [ "${{ github.event.action }}" == "package-master" ]
        then
          export USE_HEAD=true
        elif [ "${{ github.event.action }}" == "package-release" ]
        then
          export USE_HEAD=false
          export REF=`git tag --sort=committerdate --list 'v[0-9]*'|tail -1`
          git checkout $REF
          git submodule sync && git submodule update
        else
          export REF=`echo ${{ github.ref }} | sed -e 's@refs/[a-z]*/@@'`
          export USE_HEAD=true
          if [ $REF != "master" ]
          then
            export PACKAGE_UPLOAD=false
          fi
        fi
        if $USE_HEAD
        then
          echo "::set-env name=BINTRAY_REPO::multi-contact-head"
          echo "::set-env name=BINTRAY_VERSION::HEAD"
          echo "::set-env name=EXTRA_MIRROR::https://dl.bintray.com/gergondet/multi-contact-head"
          echo "::set-env name=PACKAGE_JOB::package-master"
        else
          echo "::set-env name=BINTRAY_REPO::multi-contact-release"
          echo "::set-env name=BINTRAY_VERSION::${REF}"
          echo "::set-env name=EXTRA_MIRROR::https://dl.bintray.com/gergondet/multi-contact-release"
          echo "::set-env name=PACKAGE_JOB::package-release"
        fi
        echo "::set-env name=PACKAGE_UPLOAD::${PACKAGE_UPLOAD}"
    - name: Download packages
      uses: actions/download-artifact@v1
      with:
        name: packages-${{ matrix.dist }}-${{ matrix.arch }}
      if: env.PACKAGE_UPLOAD == 'true'
    - name: Upload
      uses: jrl-umi3218/github-actions/upload-package@master
      with:
        dist: "${{ matrix.dist }}"
        arch: "${{ matrix.arch }}"
        subject: gergondet
        repo: "${{ env.BINTRAY_REPO }}"
        package: |
          name: RBDyn
          desc: "RBDyn provides a set of classes and functions to model the dynamics of rigid body systems"
          licenses: [BSD 2-Clause]
          vcs_url: https://github.com/jrl-umi3218/RBDyn
        version: "${{ env.BINTRAY_VERSION }}"
        path: packages-${{ matrix.dist }}-${{ matrix.arch }}
        BINTRAY_API_KEY: "${{ secrets.BINTRAY_API_KEY }}"
        GPG_PASSPHRASE: "${{ secrets.GPG_PASSPHRASE }}"
      if: env.PACKAGE_UPLOAD == 'true'
  mirror-sync-and-trigger:
    needs: upload-packages
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Choose extra mirror
      run: |
        # We upload in all conditions except when building on PR or branch other than master
        export PACKAGE_UPLOAD=true
        if ${{ startsWith(github.ref, 'refs/tags/') }}
        then
          export USE_HEAD=false
        elif [ "${{ github.event.action }}" == "package-master" ]
        then
          export USE_HEAD=true
        elif [ "${{ github.event.action }}" == "package-release" ]
        then
          export USE_HEAD=false
          export REF=`git tag --sort=committerdate --list 'v[0-9]*'|tail -1`
          git checkout $REF
          git submodule sync && git submodule update
        else
          export REF=`echo ${{ github.ref }} | sed -e 's@refs/[a-z]*/@@'`
          export USE_HEAD=true
          if [ $REF != "master" ]
          then
            export PACKAGE_UPLOAD=false
          fi
        fi
        if $USE_HEAD
        then
          echo "::set-env name=BINTRAY_REPO::multi-contact-head"
          echo "::set-env name=BINTRAY_VERSION::HEAD"
          echo "::set-env name=EXTRA_MIRROR::https://dl.bintray.com/gergondet/multi-contact-head"
          echo "::set-env name=PACKAGE_JOB::package-master"
        else
          echo "::set-env name=BINTRAY_REPO::multi-contact-release"
          echo "::set-env name=BINTRAY_VERSION::${REF}"
          echo "::set-env name=EXTRA_MIRROR::https://dl.bintray.com/gergondet/multi-contact-release"
          echo "::set-env name=PACKAGE_JOB::package-release"
        fi
        echo "::set-env name=PACKAGE_UPLOAD::${PACKAGE_UPLOAD}"
    - name: Request mirror sync
      run: 'curl -ugergondet:${{ secrets.BINTRAY_API_KEY }} --header "X-GPG-PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}" -X POST https://api.bintray.com/calc_metadata/gergondet/${{ env.BINTRAY_REPO }}

'
      if: env.PACKAGE_UPLOAD == 'true'
    - name: Trigger dependents rebuild
      run: 'curl -H "Accept: application/vnd.github.everest-preview+json" -H "Authorization: token ${{ secrets.GH_PAGES_TOKEN }}" --request POST --data "{\"event_type\": \"${PACKAGE_JOB}\"}" https://api.github.com/repos/jrl-umi3218/Tasks/dispatches

'
      if: env.PACKAGE_UPLOAD == 'true'
